package com.ms.www.model;

import java.util.Date;

public class RUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.fk_user_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer fkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.fk_role_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer fkRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_user_role.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer isDele;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.id
     *
     * @return the value of r_user_role.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.id
     *
     * @param id the value for r_user_role.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.fk_user_id
     *
     * @return the value of r_user_role.fk_user_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.fk_user_id
     *
     * @param fkUserId the value for r_user_role.fk_user_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setFkUserId(Integer fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.fk_role_id
     *
     * @return the value of r_user_role.fk_role_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.fk_role_id
     *
     * @param fkRoleId the value for r_user_role.fk_role_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setFkRoleId(Integer fkRoleId) {
        this.fkRoleId = fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.create_time
     *
     * @return the value of r_user_role.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.create_time
     *
     * @param createTime the value for r_user_role.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.update_time
     *
     * @return the value of r_user_role.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.update_time
     *
     * @param updateTime the value for r_user_role.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_user_role.is_dele
     *
     * @return the value of r_user_role.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getIsDele() {
        return isDele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_user_role.is_dele
     *
     * @param isDele the value for r_user_role.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setIsDele(Integer isDele) {
        this.isDele = isDele;
    }
}