package com.ms.www.model;

import java.util.Date;

public class TFunctionMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.code
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.fk_menu_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer fkMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.menu_name
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.menu_link
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private String menuLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.menu_level
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.menu_sort
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer menuSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.is_leaf
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function_menu.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    private Integer isDele;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.id
     *
     * @return the value of t_function_menu.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.id
     *
     * @param id the value for t_function_menu.id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.code
     *
     * @return the value of t_function_menu.code
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.code
     *
     * @param code the value for t_function_menu.code
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.fk_menu_id
     *
     * @return the value of t_function_menu.fk_menu_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getFkMenuId() {
        return fkMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.fk_menu_id
     *
     * @param fkMenuId the value for t_function_menu.fk_menu_id
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setFkMenuId(Integer fkMenuId) {
        this.fkMenuId = fkMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.menu_name
     *
     * @return the value of t_function_menu.menu_name
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.menu_name
     *
     * @param menuName the value for t_function_menu.menu_name
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.menu_link
     *
     * @return the value of t_function_menu.menu_link
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public String getMenuLink() {
        return menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.menu_link
     *
     * @param menuLink the value for t_function_menu.menu_link
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.menu_level
     *
     * @return the value of t_function_menu.menu_level
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.menu_level
     *
     * @param menuLevel the value for t_function_menu.menu_level
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.menu_sort
     *
     * @return the value of t_function_menu.menu_sort
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.menu_sort
     *
     * @param menuSort the value for t_function_menu.menu_sort
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.is_leaf
     *
     * @return the value of t_function_menu.is_leaf
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.is_leaf
     *
     * @param isLeaf the value for t_function_menu.is_leaf
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setIsLeaf(Integer isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.create_time
     *
     * @return the value of t_function_menu.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.create_time
     *
     * @param createTime the value for t_function_menu.create_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.update_time
     *
     * @return the value of t_function_menu.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.update_time
     *
     * @param updateTime the value for t_function_menu.update_time
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function_menu.is_dele
     *
     * @return the value of t_function_menu.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public Integer getIsDele() {
        return isDele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function_menu.is_dele
     *
     * @param isDele the value for t_function_menu.is_dele
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    public void setIsDele(Integer isDele) {
        this.isDele = isDele;
    }
}