package com.ms.www.dao;

import com.ms.www.model.RRoleMenu;
/**
 * mapper
 * @author Administrator
 *
 */
public interface RRoleMenuMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insert(RRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insertSelective(RRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    RRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKeySelective(RRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_role_menu
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKey(RRoleMenu record);
}