package com.ms.www.dao;

import com.ms.www.model.RUserRole;

public interface RUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insert(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insertSelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    RUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKeySelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKey(RUserRole record);
}