package com.ms.www.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ms.www.model.TSysUser;
import com.ms.www.util.easyui.PageHelper;

public interface TSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insert(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int insertSelective(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    TSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKeySelective(TSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user
     *
     * @mbggenerated Wed Jul 19 08:55:06 CST 2017
     */
    int updateByPrimaryKey(TSysUser record);
    
    public List<TSysUser> selectByName( String  loginname)throws Exception;
    
    
    public Long getDatagridTotal(@Param("user")TSysUser user);

	public List<TSysUser> datagridUser(@Param("page")PageHelper page,@Param("user")TSysUser user);
	
	
	public List getUserAll();
    
}